import type { Level } from "./types";

export const LEVELS: Level[] = [
  {
    code: "GAME 01",
    title: "THE FIRST DOOR",
    topic: "Propositions & Logical Operators",
    env: "doors",
    timeLimit: 300,
    required: 5,
    hostIntro: ["Every door has a statement.", "Only one statement is true.", "Reason carefully, Player 047."],
    questions: [
      {
        id: "g1q1", concept: "Propositions",
        prompt: "Which of the following is a proposition?",
        options: ["Close the door.", "7 is a prime number.", "Is it raining?", "x + 2 = 5"],
        answer: 1,
        steps: [
          "A proposition is a declarative sentence that is either TRUE or FALSE, but not both.",
          "\"Close the door.\" is a command — no truth value.",
          "\"Is it raining?\" is a question — no truth value.",
          "\"x + 2 = 5\" depends on x — it is an open sentence (predicate).",
          "\"7 is a prime number\" is a statement with a definite value: TRUE.",
        ],
      },
      {
        id: "g1q2", concept: "Logical AND (Conjunction)",
        prompt: "Evaluate the expression.",
        given: ["P = TRUE", "Q = FALSE"], expr: "P ∧ Q",
        options: ["TRUE", "FALSE"], answer: 1,
        steps: ["P = TRUE", "Q = FALSE", "P ∧ Q is TRUE only when both P and Q are TRUE.", "Q is FALSE.", "Therefore: P ∧ Q = FALSE"],
      },
      {
        id: "g1q3", concept: "Logical OR (Disjunction)",
        prompt: "Evaluate the expression.",
        given: ["P = TRUE", "Q = FALSE"], expr: "P ∨ Q",
        options: ["TRUE", "FALSE"], answer: 0,
        steps: ["P = TRUE", "Q = FALSE", "P ∨ Q is TRUE when at least one of P, Q is TRUE.", "P is TRUE.", "Therefore: P ∨ Q = TRUE"],
      },
      {
        id: "g1q4", concept: "Negation (NOT)",
        prompt: "Evaluate the expression.",
        given: ["P = FALSE", "Q = TRUE"], expr: "¬P ∧ Q",
        options: ["TRUE", "FALSE"], answer: 0,
        steps: ["P = FALSE, so ¬P = TRUE (negation flips the value).", "Q = TRUE", "¬P ∧ Q = TRUE ∧ TRUE", "Therefore: TRUE"],
      },
      {
        id: "g1q5", concept: "Implication (Conditional)",
        prompt: "Evaluate the conditional.",
        given: ["P = TRUE", "Q = FALSE"], expr: "P → Q",
        options: ["TRUE", "FALSE"], answer: 1,
        steps: ["P → Q is FALSE only when P is TRUE and Q is FALSE.", "Here P = TRUE and Q = FALSE.", "The promise is broken.", "Therefore: P → Q = FALSE"],
      },
      {
        id: "g1q6", concept: "Implication — Vacuous Truth",
        prompt: "Evaluate the conditional.",
        given: ["P = FALSE", "Q = FALSE"], expr: "P → Q",
        options: ["TRUE", "FALSE"], answer: 0,
        steps: ["P → Q is FALSE only in the case T → F.", "Here the hypothesis P is FALSE.", "A conditional with a false hypothesis is vacuously TRUE.", "Therefore: P → Q = TRUE"],
      },
      {
        id: "g1q7", concept: "Compound Expressions",
        prompt: "Evaluate the compound expression.",
        given: ["P = TRUE", "Q = TRUE", "R = FALSE"], expr: "(P ∧ Q) ∨ R",
        options: ["TRUE", "FALSE"], answer: 0,
        steps: ["Evaluate parentheses first: P ∧ Q = TRUE ∧ TRUE = TRUE", "Then: TRUE ∨ R = TRUE ∨ FALSE", "OR needs at least one TRUE.", "Therefore: TRUE"],
      },
    ],
  },
  {
    code: "GAME 02",
    title: "THE TRUTH ROOM",
    topic: "Truth Tables",
    env: "control",
    timeLimit: 300,
    required: 5,
    hostIntro: ["Every screen shows a fragment of a system.", "Some systems are valid. Some are broken.", "Read the tables."],
    questions: [
      {
        id: "g2q1", concept: "Size of a Truth Table",
        prompt: "A compound proposition uses 3 variables: P, Q, R. How many rows does its truth table have?",
        options: ["3", "6", "8", "9"], answer: 2,
        steps: ["Each variable has 2 possible truth values.", "For n variables the number of rows is 2ⁿ.", "2³ = 2 × 2 × 2 = 8", "Therefore: 8 rows"],
      },
      {
        id: "g2q2", concept: "Truth Table of Implication",
        prompt: "Complete the output column of P → Q for the rows (P,Q) = TT, TF, FT, FF.",
        expr: "P → Q",
        options: ["T, F, T, T", "T, F, F, F", "T, T, T, F", "F, T, T, T"], answer: 0,
        steps: ["TT: T → T = T", "TF: T → F = F (the only false case)", "FT: F → T = T (vacuous)", "FF: F → F = T (vacuous)", "Column: T, F, T, T"],
      },
      {
        id: "g2q3", concept: "Tautology",
        prompt: "Classify the proposition.",
        expr: "P ∨ ¬P",
        options: ["Tautology", "Contradiction", "Contingency"], answer: 0,
        steps: ["Row P = T: T ∨ F = T", "Row P = F: F ∨ T = T", "TRUE in every row.", "A proposition true in all rows is a TAUTOLOGY."],
      },
      {
        id: "g2q4", concept: "Contradiction",
        prompt: "Classify the proposition.",
        expr: "P ∧ ¬P",
        options: ["Tautology", "Contradiction", "Contingency"], answer: 1,
        steps: ["Row P = T: T ∧ F = F", "Row P = F: F ∧ T = F", "FALSE in every row.", "A proposition false in all rows is a CONTRADICTION."],
      },
      {
        id: "g2q5", concept: "Truth Table of NOR",
        prompt: "Complete the output column of ¬(P ∨ Q) for the rows (P,Q) = TT, TF, FT, FF.",
        expr: "¬(P ∨ Q)",
        options: ["F, F, F, T", "T, T, T, F", "F, T, T, T", "T, F, F, F"], answer: 0,
        steps: ["First compute P ∨ Q: T, T, T, F", "Negate each value.", "¬(P ∨ Q): F, F, F, T", "It is TRUE only when both are FALSE."],
      },
      {
        id: "g2q6", concept: "Biconditional",
        prompt: "In the row where P = TRUE and Q = FALSE, what is the value?",
        given: ["P = TRUE", "Q = FALSE"], expr: "P ↔ Q",
        options: ["TRUE", "FALSE"], answer: 1,
        steps: ["P ↔ Q is TRUE when P and Q have the same value.", "P = TRUE, Q = FALSE — different values.", "Therefore: FALSE"],
      },
      {
        id: "g2q7", concept: "Contingency",
        prompt: "Classify the proposition.",
        expr: "P → Q",
        options: ["Tautology", "Contradiction", "Contingency"], answer: 2,
        steps: ["Column of P → Q: T, F, T, T", "It is TRUE in some rows and FALSE in at least one.", "Not always true, not always false.", "Therefore: CONTINGENCY"],
      },
    ],
  },
  {
    code: "GAME 03",
    title: "THE MIRROR CHAMBER",
    topic: "Logical Equivalence",
    env: "mirror",
    timeLimit: 300,
    required: 5,
    hostIntro: ["Two walls. Two reflections.", "Some reflections are honest.", "Decide which ones are the same."],
    questions: [
      {
        id: "g3q1", concept: "De Morgan's Law (AND)",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["¬(P ∧ Q)", "¬P ∨ ¬Q"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 0,
        steps: ["De Morgan's Law: ¬(P ∧ Q) ≡ ¬P ∨ ¬Q", "Check P=T, Q=T: ¬(T) = F and F ∨ F = F ✓", "Check P=T, Q=F: ¬(F) = T and F ∨ T = T ✓", "All rows match.", "Therefore: EQUIVALENT"],
      },
      {
        id: "g3q2", concept: "De Morgan's Law (misapplied)",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["¬(P ∨ Q)", "¬P ∨ ¬Q"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 1,
        steps: ["Correct law: ¬(P ∨ Q) ≡ ¬P ∧ ¬Q (the OR becomes AND).", "Counterexample P=T, Q=F:", "¬(T ∨ F) = ¬T = F", "¬T ∨ ¬F = F ∨ T = T", "F ≠ T, therefore NOT EQUIVALENT"],
      },
      {
        id: "g3q3", concept: "Implication Equivalence",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["P → Q", "¬P ∨ Q"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 0,
        steps: ["P → Q is FALSE only when P = T, Q = F.", "¬P ∨ Q is FALSE only when ¬P = F and Q = F, i.e. P = T, Q = F.", "Same single false row.", "Therefore: P → Q ≡ ¬P ∨ Q"],
      },
      {
        id: "g3q4", concept: "Converse",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["P → Q", "Q → P"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 1,
        steps: ["Q → P is the CONVERSE of P → Q.", "Counterexample P=F, Q=T:", "P → Q = F → T = T", "Q → P = T → F = F", "Therefore: NOT EQUIVALENT"],
      },
      {
        id: "g3q5", concept: "Contrapositive",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["P → Q", "¬Q → ¬P"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 0,
        steps: ["¬Q → ¬P is the CONTRAPOSITIVE of P → Q.", "¬Q → ¬P ≡ ¬¬Q ∨ ¬P ≡ Q ∨ ¬P", "P → Q ≡ ¬P ∨ Q", "Same expression.", "Therefore: EQUIVALENT"],
      },
      {
        id: "g3q6", concept: "Double Negation",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["¬(¬P)", "P"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 0,
        steps: ["P = T: ¬T = F, ¬F = T ✓", "P = F: ¬F = T, ¬T = F ✓", "Negating twice returns the original value.", "Therefore: EQUIVALENT (Double Negation Law)"],
      },
      {
        id: "g3q7", concept: "Tautology Equivalence",
        prompt: "Are these two expressions logically equivalent?",
        pair: ["P ∨ ¬P", "P ∧ ¬P"],
        options: ["EQUIVALENT", "NOT EQUIVALENT"], answer: 1,
        steps: ["P ∨ ¬P is a tautology — always T.", "P ∧ ¬P is a contradiction — always F.", "Their columns never match.", "Therefore: NOT EQUIVALENT"],
      },
    ],
  },
  {
    code: "GAME 04",
    title: "THE FINAL JUDGMENT",
    topic: "Rules of Inference",
    env: "arena",
    timeLimit: 420,
    required: 7,
    hostIntro: ["This is the final game.", "Premises will be given.", "Only valid conclusions survive."],
    questions: [
      {
        id: "g4q1", concept: "Modus Ponens",
        prompt: "What conclusion follows?",
        premises: ["If it rains, the ground is wet.", "It rains."],
        options: ["The ground is wet.", "The ground is not wet.", "It does not rain.", "No conclusion."], answer: 0,
        steps: ["Let P: it rains, Q: the ground is wet.", "Premise 1: P → Q", "Premise 2: P", "Modus Ponens: from P → Q and P infer Q."],
        chain: { premise: ["P → Q", "P"], rule: "Modus Ponens", conclusion: "Q — the ground is wet" },
      },
      {
        id: "g4q2", concept: "Modus Tollens",
        prompt: "What conclusion follows?",
        premises: ["If Ana studies, she passes.", "Ana did not pass."],
        options: ["Ana studied.", "Ana did not study.", "Ana will pass next time.", "No conclusion."], answer: 1,
        steps: ["Let P: Ana studies, Q: Ana passes.", "Premise 1: P → Q", "Premise 2: ¬Q", "Modus Tollens: from P → Q and ¬Q infer ¬P."],
        chain: { premise: ["P → Q", "¬Q"], rule: "Modus Tollens", conclusion: "¬P — Ana did not study" },
      },
      {
        id: "g4q3", concept: "Invalid Inference — Affirming the Consequent",
        prompt: "Is this argument valid?",
        premises: ["P → Q", "Q", "∴ P"],
        options: ["VALID", "INVALID"], answer: 1,
        steps: ["Counterexample: P = F, Q = T.", "P → Q = F → T = T ✓ (premise true)", "Q = T ✓ (premise true)", "Conclusion P = F ✗", "True premises, false conclusion → INVALID (Fallacy of affirming the consequent)."],
        chain: { premise: ["P → Q", "Q"], rule: "Affirming the Consequent (fallacy)", conclusion: "P does NOT follow" },
      },
      {
        id: "g4q4", concept: "Invalid Inference — Denying the Antecedent",
        prompt: "Is this argument valid?",
        premises: ["P → Q", "¬P", "∴ ¬Q"],
        options: ["VALID", "INVALID"], answer: 1,
        steps: ["Counterexample: P = F, Q = T.", "P → Q = T ✓, ¬P = T ✓", "Conclusion ¬Q = F ✗", "Therefore INVALID (Fallacy of denying the antecedent)."],
        chain: { premise: ["P → Q", "¬P"], rule: "Denying the Antecedent (fallacy)", conclusion: "¬Q does NOT follow" },
      },
      {
        id: "g4q5", concept: "Disjunctive Syllogism",
        prompt: "What conclusion follows?",
        premises: ["The key is in the red box or the blue box.", "The key is not in the red box."],
        options: ["The key is in both boxes.", "The key is in the blue box.", "The key is nowhere.", "No conclusion."], answer: 1,
        steps: ["Let P: red box, Q: blue box.", "Premise 1: P ∨ Q", "Premise 2: ¬P", "Disjunctive Syllogism: from P ∨ Q and ¬P infer Q."],
        chain: { premise: ["P ∨ Q", "¬P"], rule: "Disjunctive Syllogism", conclusion: "Q — the key is in the blue box" },
      },
      {
        id: "g4q6", concept: "Hypothetical Syllogism",
        prompt: "What conclusion follows?",
        premises: ["P → Q", "Q → R"],
        options: ["R → P", "P → R", "Q", "P ∧ R"], answer: 1,
        steps: ["Premise 1: P → Q", "Premise 2: Q → R", "Chain the implications through Q.", "Hypothetical Syllogism: infer P → R."],
        chain: { premise: ["P → Q", "Q → R"], rule: "Hypothetical Syllogism", conclusion: "P → R" },
      },
      {
        id: "g4q7", concept: "Simplification",
        prompt: "Which rule justifies this step?",
        premises: ["P ∧ Q", "∴ P"],
        options: ["Addition", "Simplification", "Conjunction", "Modus Ponens"], answer: 1,
        steps: ["If P ∧ Q is TRUE, both P and Q are TRUE.", "So P alone may be concluded.", "This rule is Simplification."],
        chain: { premise: ["P ∧ Q"], rule: "Simplification", conclusion: "P" },
      },
      {
        id: "g4q8", concept: "Multi-step Reasoning (MP + MP)",
        prompt: "What can be concluded?",
        premises: ["P → Q", "Q → R", "P"],
        options: ["¬R", "R", "¬P", "No conclusion"], answer: 1,
        steps: ["Step 1: P → Q and P ⟹ Q (Modus Ponens)", "Step 2: Q → R and Q ⟹ R (Modus Ponens)", "Therefore: R"],
        chain: { premise: ["P → Q", "Q → R", "P"], rule: "Modus Ponens ×2", conclusion: "R" },
      },
      {
        id: "g4q9", concept: "Multi-step Reasoning (MT + DS)",
        prompt: "What can be concluded?",
        premises: ["P → Q", "¬Q", "P ∨ S"],
        options: ["P", "Q", "S", "¬S"], answer: 2,
        steps: ["Step 1: P → Q and ¬Q ⟹ ¬P (Modus Tollens)", "Step 2: P ∨ S and ¬P ⟹ S (Disjunctive Syllogism)", "Therefore: S"],
        chain: { premise: ["P → Q", "¬Q", "P ∨ S"], rule: "Modus Tollens → Disjunctive Syllogism", conclusion: "S" },
      },
    ],
  },
];
